### ISSUE TITLE
Cannot clone on windows

### ISSUE THREAD

**Issue by metalbass** [kikeelectronico/Homeware-LAN#10]
It seems like aux is a reserved word in the file system, which is reserved:

https://stackoverflow.com/questions/36225708/cannot-create-a-directory-named-aux-or-starting-by-aux-on-windows-8-1

Then, it's unable to create a file called aux.py beacause of this.

**Comment by kikeelectronico** [comment]
Done. It will be available on release v0.2. Provably tomorrow 9/02/2020.
