### ISSUE TITLE
Conexión ESP<-> HOMEWARE_LAN 

### ISSUE THREAD

**Issue by lucasdellasantina96** [kikeelectronico/Homeware-LAN#150]
No puedo conectar el ejemplo disponible de la repo (ejemplo esp8266 )al server mqtt.
Puse el mismo Client ID en la esp como en el dispositivo de HOMEWARE
Luego me pude a buscar el funcionamiento del le función client.connect que si no se donde poner los datos del el pasword del MQTT por que en función  client.connect("", ID, PASSWORD))  tendría que pasarle esos parámetros, así también los  los tópicos de publish ?
 
El error que me devuelve la esp es :
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds

**Comment by kikeelectronico** [comment]
En principio solo tienes que pasar el usuario NY contraseña en el método _connect_.

```
client.connect(clientId.c_str(), "user", "pass")
```

**Comment by lucasdellasantina96** [comment]
Perfecto, logre conectar el dispositivo al server pero ahora no puedo conectar  Google home con el server 
Le adjunto un rec-screen del problema
 
https://drive.google.com/file/d/14MUQjQxnpU5Tt2xQK7BKBPjnk-ByCyQW/view?usp=sharing

**Comment by kikeelectronico** [comment]
Verifica que no haya algún dispositivo con nombres incorrectos. Entra uno a uno en su sección _info_ (devices/info/ide-dispositivo) y verifica que tiene una sección _defaultNames_ en lugar de _defaultnames_ y una sección _nicknames_ en lugar de _nickNames_.

**Comment by kikeelectronico** [comment]
Solucionado en https://github.com/kikeelectronico/Homeware-LAN/issues/157#issuecomment-724383135
