### ISSUE TITLE
problemas con la pantalla de login

### ISSUE THREAD

**Issue by messplay** [kikeelectronico/Homeware-LAN#157]
Hola resulta que el dia de ayer desvincule el dispositivo en medio de unas prubas... al intentar vincularlo nuevamente llego a la pagina donde se ingresa el usario y la contraseña, los ingreso normalmente y cuando le doy al boton de login no acepta la orden, es como si el boton "no hiciera click" lo intente desde mi pc y es el mismo comportamiento, alguna idea de que puede ser?

**Comment by kikeelectronico** [comment]
Creo que tienes el mismo problema que en #150

"Verifica que no haya algún dispositivo con nombres incorrectos. Entra uno a uno en su sección info (devices/info/ide-dispositivo) y verifica que tiene una sección defaultNames en lugar de defaultnames y una sección nicknames en lugar de nickNames."

**Comment by lucasdellasantina96** [comment]
https://drive.google.com/file/d/102ejBOQyVlkivYWP75ruIp7Wc3dBYBx6/view?usp=sharing 

Efectivamente hay un sección con nikename, quedaría modificar eso pero no tengo mucha idea de como hacerlo  !

**Comment by kikeelectronico** [comment]
Parece correcto. Veo que ese es el dispositivo de ejemplo. Elimínalo y vuelve a probar a sincronizar.

Verifica que todo está bien configurado en la página de _Settings_. Sobre todo la información de conexión con Google.

**Comment by lucasdellasantina96** [comment]
Encontré el problema,  me comí una letra en url  Fulfillment   busque por todos lados y no vi lo obvio! GRACIAS

La semana que viene si tengo tiempo subo un video como se configura todo para gente colgada como yo jajaja

https://console.actions.google.com/u/0/  --> develop

**Comment by kikeelectronico** [comment]
Perfecto @lucasdellasantina96

**Comment by messplay** [comment]
Bueno al parecer si era un problema de compatibilidad con la importacion del back up, sin embargo se soluciono volviendo a correr el script de instalacion. Como ya lo mencione estoy corriendo en una RPI W Zero y con los bombillos de la sala corre perfecto, Ahora seguir con el reto de hacerlo compatible con sensores mas complejos como GNSS de precision
