### ISSUE TITLE
[Feature] Devices feedback

### ISSUE THREAD

**Issue by kikeelectronico** [kikeelectronico/Homeware-LAN#175]
**Is your feature request related to a problem? Please describe.**
I can't see clearly the status of some devices at Devices tab.

**Describe the solution you'd like**
I would like to see status feedback of all devices at Devices tab.

**Describe alternatives you've considered**
F.E.: Scene could have a color strip to indicate if it is enabled or not

**Additional context**
-

**Comment by Hassesinoserver** [comment]
hola enrique, veras no logro que home app me deje logear, me da error 500%, lo eh intentado desde el principio en varias ocasiones reinstalando todo con correos nuevos, no hay manera.

**Comment by kikeelectronico** [comment]
Hola @Hassesinoserver por favor, traslada tu duda a https://github.com/kikeelectronico/Homeware-LAN/discussions al crearla usa la sección de Q&A.

Intenta borrar la cache de la app. Si no funciona, me cuentas desde https://github.com/kikeelectronico/Homeware-LAN/discussions , adjuntas una captura de pantalla y seguimos trabajando hasta encontrar el problema.
