### ISSUE TITLE
How to change username/password for admin

### ISSUE THREAD

**Issue by readylan** [kikeelectronico/Homeware-LAN#230]
Hello!

I have installed Homeware-LAN and the system prompt for the username/pass to log in. However when I try to log in, the web page shows "Incorrect user or password". I may not remember the correct credentials but, in any case, how could I reset them?

Regards,

Eduardo

**Comment by GuillermoSP96** [comment]
The information you can see in the **homeware.json** file, it is located in **/usr/share/Homeware-LAN**
the password is hash. You can delete the hash and try login with empty password. I don't know if it works

**Comment by GuillermoSP96** [comment]
Or you can create an python scrypt 
`import bcrypt`
`incommingData="Here your password"`
`print(str(bcrypt.hashpw(incommingData.encode('utf-8'), bcrypt.gensalt())))`
Execute this scrypt and copy the value in the _/usr/share/Homeware-LAN/homeware.json__ --> **("pass": "b'$2b$12$HqQEjTV6IheBM4Fd4eHsXOL5XV3zd.9JHnqebPapSBn/NwqoFHtTa'"**)
Save the homeware.json file and restart your services. And you use the new password to login.

**Comment by kikeelectronico** [comment]
You can find the instructions here https://kikeelectronico.github.io/Homeware-LAN/docs/reset-user
