### ISSUE TITLE
bug al crear nuevos dispositivos 

### ISSUE THREAD

**Issue by lucasdellasantina96** [kikeelectronico/Homeware-LAN#233]
Hola buenos dias, al generar nuevos tópicos se anidan en otros ya existentes, mi consulta es esto esta bien ? o es un bug.
 Por que estoy tratando de realizar un script y cada ves que genero un nuevo dispositivo se me generan un nuevo objet en .json , lo podría descartar pero si borro un dispositivo creado anteriormente pierdo la referencia.  Les dejo una imagen donde se puede ver que light se anida dentro  de AC_01  y que aire_test dentro de AC_01

![image](https://user-images.githubusercontent.com/25237943/103910018-1c728e80-50e3-11eb-9d3f-b15b49434921.png)
![image](https://user-images.githubusercontent.com/25237943/103911311-9e16ec00-50e4-11eb-91bb-bb2447017dc3.png)

**Comment by lucasdellasantina96** [comment]
como que al crear un dispositivo nuevo no figura en el tópico, pero si figura el anterior y así sucesivamente, como que figura el n-1, es algo muy raro no termino de comprender donde esta el error

**Comment by kikeelectronico** [comment]
Corregido en la versión v1.1.4 https://github.com/kikeelectronico/Homeware-LAN/releases/tag/v1.1.4
