### ISSUE TITLE
Google Home no conecta con Homeware

### ISSUE THREAD

**Issue by sami1501** [kikeelectronico/Homeware-LAN#234]
Hola,

Mi instalación de Homeware-Lan estaba funcionando perfectamente. Tenía un device creado que no se podía borrar ya que el botón de Eliminar no funcionaba así que intenté probar a desvincular la cuenta e intentarla volver a vincularla, pero a partir de ahí Google Home ya no quiere conectarse a Homeware-Lan. He dejado un video en mi drive de google: https://drive.google.com/file/d/1Yrvm4QKlhpf1rX_FEUUOx4FO-6tpDtdq/view?usp=sharing

Es muy extraño porque he formateado la tarjeta de la raspberry y vuelto a instalar todo y sigue sin funcionar. Además he intentado hacer la conexión con otro teléfono y tampoco funciona.

Muchas gracias

**Comment by lucasdellasantina96** [comment]
hola, corrobora de tener el los pasos de https://kikeelectronico.github.io/Homeware-LAN/docs/connect-with-google bien hechos, a mi me paso por que tenia mal el Fulfillment URL, (nota al margen se pueden subir videos a GitHub yo tampoco sabia ;)) )

**Comment by kikeelectronico** [comment]
Verifica que puedes hacer login en tu instalación de Homeware desde ese smartphone y tal y como dice lucasdellasantina96, revisa que todos los enlaces son correctos (incluidos https:// y la barra final de las URL). Es extraño que ocurra algo así.

**Comment by kikeelectronico** [comment]
Imagino que o se ha solucionado el problema o no se a continuado evaluando. Cierro la isuue. Sentíos libres de abrirla de nuevo si es necesario.
