### ISSUE TITLE
[Feature] Dockerize Homeware-LAN

### ISSUE THREAD

**Issue by ajpl** [kikeelectronico/Homeware-LAN#255]
**Is your feature request related to a problem? Please describe.**
You have to deploy to a bare metal server and install services to the host. Thus making the whole experience "slower" and more difficult to get rid off in case of wanting to uninstall. (e.g. installing a `redis` server in the host)

**Describe the solution you'd like**
I'd like for Homeware-LAN to be dockerized. An image for Homeware-LAN should be created so that it can be brought up on its own within an already existent containerized environment. Also a `docker-compose` could be created to provision a `redis` server for a quicker 0 to 100% experience.

**Describe alternatives you've considered**

1. Create a `Dockerfile` for Homeware-LAN.
2. Build & Push the image to GHs or Docker Hub's Registries every time there is a commit to master / release via an automation using Github Workflows
3. Create a `docker-compose` file with all the necessary dependencies to bring Homeware-LAN up

**Additional context**
I have knowledge with the matter at hand and if welcomed, I offer myself to author a PR with the changes.

**Comment by kikeelectronico** [comment]
@ajpl it sounds interesting. It would be awesome if you contribute with the PR to build and push the image to GitHub Packages. Let me know if you need anything like a secret for the workflow.

**Comment by betojsp** [comment]
@ajpl I can help you by building the docker-compose and testing

**Comment by ajpl** [comment]
@betojsp I already laid some groundwork [over here](https://github.com/ajpl/Homeware-LAN/tree/docker). Led me go ahead and create a PR...

**Comment by ajpl** [comment]
Hi @kikeelectronico could you please create a new token. Per [this instructions](https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages) ? Thank you !

**Comment by kikeelectronico** [comment]
Hi @ajpl great work!

Done. You can use ${{ secrets.PACKAGES_TOKEN }}. It should have the correct permissions.

Thank you!

**Comment by ajpl** [comment]
Hi @kikeelectronico and @betojsp, please take a look at the PR(#265) and test it if you can. Also [notice this](https://github.com/kikeelectronico/Homeware-LAN/pull/265#issuecomment-782352789) before you do any tests.

**Comment by ajpl** [comment]
I successfuly got the project running on a fresh Digital Ocean droplet without any issues 😃

**Comment by betojsp** [comment]
Hi @ajpl and @kikeelectronico, I comment step by step what I did

````
# git clone --branch docker https://github.com/ajpl/Homeware-LAN.git
# cd Homeware-LAN
# docker-composer up --build
ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./docker-compose.yaml", line 57, column 7
````

I change "1883":"1883" to "1883:1883", 

**Try again ...**
````
# docker-compose up --build
Pulling homeware-lan-back-mqtt (ghcr.io/kikeelectronico/homewarelan-back:)...
ERROR: Head https://ghcr.io/v2/kikeelectronico/homewarelan-back/manifests/latest: denied
````

I don't know if this step is the correct one
````
# docker login ghcr.io --username betojsp
Password:
Error response from daemon: Get https://ghcr.io/v2/: denied: denied
````
😃

**Comment by ajpl** [comment]
Oh I'll fix that typo on the docker compose yaml. Please also notice the following https://github.com/kikeelectronico/Homeware-LAN/pull/265#issuecomment-782352789 , you should also change the image source up until this has been merged. That will get you going.

**Comment by kikeelectronico** [comment]
Awesome. I'll take a look ASAP.

**Comment by ajpl** [comment]
Led me know if you need any extra help making it work / testing .

**Comment by betojsp** [comment]
I am trying to deploy on an **arm** processor, it is clear that I have to create the img from the Dockerfiles. I try to continue testing today.

**Comment by ajpl** [comment]
The images [are built](https://github.com/kikeelectronico/Homeware-LAN/pull/265/files#diff-262d44eaf4bec1ca370d4ecd6e380b70cab17f0150e848c894cddfcfff89bcbfR101) for `linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64`. Are you using another ARM processor not listed there ?

**Comment by betojsp** [comment]
**model name      : ARMv7 Processor rev 10 (v7l)**

The error is reported by the conteiner nginx-proxy (jwilder/nginx-proxy) to create de letsecrypt certified

standard_init_linux.go:219: exec user process caused: exec format error

**Comment by kikeelectronico** [comment]
@ajpl something went wrong during the release: https://github.com/kikeelectronico/Homeware-LAN/runs/1995343825?check_suite_focus=true

**Comment by ajpl** [comment]
I can't see the build output. Could you please copy and paste it here? Thanks

**Comment by kikeelectronico** [comment]
Run docker/build-push-action@v2
  with:
    context: .
    file: ./Dockerfile-back
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
    push: true
    tags: ghcr.io/kikeelectronico/homewarelan-back:latest
  ghcr.io/kikeelectronico/homewarelan-back:0fcc73ddc9e81e4b14273c0a1c3cd390bde93fd1
  ghcr.io/kikeelectronico/homewarelan-back:{
    "url": "https://api.github.com/repos/kikeelectronico/Homeware-LAN/releases/39001273",
    "assets_url": "https://api.github.com/repos/kikeelectronico/Homeware-LAN/releases/39001273/assets",
    "upload_url": "https://uploads.github.com/repos/kikeelectronico/Homeware-LAN/releases/39001273/assets{?name,label}",
    "html_url": "https://github.com/kikeelectronico/Homeware-LAN/releases/tag/v1.3",
    "id": 39001273,
    "author": {
      "login": "kikeelectronico",
      "id": 4513513,
      "node_id": "MDQ6VXNlcjQ1MTM1MTM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4513513?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kikeelectronico",
      "html_url": "https://github.com/kikeelectronico",
      "followers_url": "https://api.github.com/users/kikeelectronico/followers",
      "following_url": "https://api.github.com/users/kikeelectronico/following{/other_user}",
      "gists_url": "https://api.github.com/users/kikeelectronico/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kikeelectronico/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kikeelectronico/subscriptions",
      "organizations_url": "https://api.github.com/users/kikeelectronico/orgs",
      "repos_url": "https://api.github.com/users/kikeelectronico/repos",
      "events_url": "https://api.github.com/users/kikeelectronico/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kikeelectronico/received_events",
      "type": "User",
      "site_admin": false
    },
    "node_id": "MDc6UmVsZWFzZTM5MDAxMjcz",
    "tag_name": "v1.3",
    "target_commitish": "master",
    "name": "New features and docker install",
    "draft": false,
    "prerelease": false,
    "created_at": "2021-02-27T20:16:32Z",
    "published_at": "2021-02-27T20:18:30Z",
    "assets": [],
    "tarball_url": "https://api.github.com/repos/kikeelectronico/Homeware-LAN/tarball/v1.3",
    "zipball_url": "https://api.github.com/repos/kikeelectronico/Homeware-LAN/zipball/v1.3",
    "body": "Wait, do not update. I am testing things. Come back later."
  }
  
    pull: false
    no-cache: false
    load: false
    github-token: ***
  env:
    working-directory: ./front
📣 Buildx version: 0.5.1
Error: Invalid Opening Quote: a quote is found inside a field at line 4

**Comment by ajpl** [comment]
This #275 should fix it, sorry for the inconvenience.

**Comment by kikeelectronico** [comment]
Merged, tested and released. Thanks @ajpl. It is a great upgrade.
