### ISSUE TITLE
[BUG] imposible clonar el proyecto en Windows

### ISSUE THREAD

**Issue by ricofairsailcom** [kikeelectronico/Homeware-LAN#266]
**Describe el bug**
No se puede descargar el codigo in ordenadores Windows

**Para reproducir**
Pasos para reproducir el bug:
1. clonar el proyecto en una máquina con windows 8 en adelante (actualmente uso W10)

**Comportamiento esperado**
descarga del codigo

**Capturas de pantalla**
https://stackoverflow.com/questions/36225708/cannot-create-a-directory-named-aux-or-starting-by-aux-on-windows-8-1

**Comment by ricofairsailcom** [comment]
He intentado arreglarlo pero recibo este error: fatal: unable to access 'https://github.com/kikeelectronico/Homeware-LAN.git/': The requested URL returned error: 403

**Comment by lucasdellasantina96** [comment]
Hola, como esta?  creo que la repo esta creada para linux, ubuntu y bsd (actualmente la tengo corriendo en esta), desconozco si es compatible con Windows pero por lo que tengo entendido hay funciones las cuales corren con systemctrl, nginx y scpits en bash(tocamos algunas para que funcione en bsd), por lo cual dudo mucho que sea compatible con Windows sin modificar nada.

**Comment by ricofairsailcom** [comment]
Gracias @lucasdellasantina96 solo quería descargar el codigo para ver que había actualmente implementado. Al ser un proyecto Python pensé que sería buena idea permitir descargar y ejecutarlo tambien en máquinas Windowns. Pero le dejo la decisión a @kikeelectronico ;)

**Comment by lucasdellasantina96** [comment]
Estaría muy bueno  hacer una rama  para que funcione en Windows, aunque de mi parte no tengo idea como se podría implementar

**Comment by ajpl** [comment]
Cuando el PR #265 ( issue #255 ) este en `master` el proyecto va a poder ser levantado desde Windows mediante Docker Compose.

**Comment by kikeelectronico** [comment]
He desplegado #256, así que, usando los commandos adecuados para Windows, deberíais poder usar Docker en Windows https://kikeelectronico.github.io/Homeware-LAN/docs/install

**Comment by kikeelectronico** [comment]
@ricofairsailcom pudiste desplegarlo?
