### ISSUE TITLE
Auto login 

### ISSUE THREAD

**Issue by lucasdellasantina96** [kikeelectronico/Homeware-LAN#267]
La idea principal es guardar las contraseñas en el gestor de contraseñas del navegador por ejemplo google Chrome, generar un acceso directo a la URL y se podría utilizar como aplicación en la cual no se tenga que logear cada vez que uno entra.

Por lo que estuve leyendo es posible, dejo la repo mediante la cual creo que se puede hacer https://github.com/ralscha/blog2019/tree/master/credential/server

**Comment by lucasdellasantina96** [comment]
https://golb.hplar.ch/2019/06/credential-management-api.html

**Comment by kikeelectronico** [comment]
Lo reviso.

**Comment by kikeelectronico** [comment]
Hecho. A partir de v1.4 los gestores de contraseñas pueden realizar autologin
