### ISSUE TITLE
AC_unit

### ISSUE THREAD

**Issue by lucasdellasantina96** [kikeelectronico/Homeware-LAN#268]
Hola, como estan ?
Me surgió este problema:
si declaro el dispositivo como termostato no me figura el botón de encendido, en cambio si lo pongo como unidad de aire acondicionado el dispositivo 567  si lo puedo hacer, pero en este modo no puedo configurar la temperatura desde home, Saben como lo podría corregir ? o alguna idea 

![image](https://user-images.githubusercontent.com/25237943/108574424-26003080-72f6-11eb-9ece-5af29ff5e7f7.png)

**Comment by kikeelectronico** [comment]
El termostato no tiene el trait on/off como recomendado. Por lo que técnicamente no se puede encender o apagar, solo cambiar su estado entre calor, frío, etc.
