### ISSUE TITLE
Estoy teniendo este problema al tratar de cambiar de modo del termostato 

### ISSUE THREAD

**Issue by lucasdellasantina96** [kikeelectronico/Homeware-LAN#277]
Estoy teniendo este problema, igualmente al tratar de cambiar de modo no cambia, lo que se me ocurre que por el lado del dispositivo tenga alguna confirmación de modo, lo cual tendría q hacer un publish?

La idea principalmente es   hacer un scrip en python para integrar a Google home un aire que se administra por una pagina  lo cual ya lo logre  hacer con curl pero tengo este inconveniente y no se como solucionarlo (al no quedar on el termostato no puedo modificar la temperatura)

![image](https://user-images.githubusercontent.com/25237943/110706364-7fad9980-81d6-11eb-859a-23b49daefdb4.png)

https://user-images.githubusercontent.com/25237943/110705370-111c0c00-81d5-11eb-83b8-e64838f5891d.mp4

_Originally posted by @lucasdellasantina96 in https://github.com/kikeelectronico/Homeware-LAN/discussions/270#discussioncomment-465743_

**Comment by kikeelectronico** [comment]
Solucionado v 1.4
