### ISSUE TITLE
Compatibilidad con duckdns y otros proveedores de DDNS

### ISSUE THREAD

**Issue by ljcmps01** [kikeelectronico/Homeware-LAN#278]
**¿Está la nueva característica relacionada con un problema? Por favor, descríbelo.**
Tengo configurado mi DDNS con Duckdns, sin embargo a la hora de configurar el servidor en Homeware, la única opción de proveedor disponible es no-IP

**Describe la solución que te gustaría**
Añadir compatibilidad con DuckDNS si es posible

**Describe que alternativas has considerado**
Por ahora utilizaré no-IP pero seria ideal utilizar DuckDNS ya que, por lo menos en mi opinión, desde el lado del usuario la configuración es mas simple

**Comment by kikeelectronico** [comment]
Incluido, gracias por el aporte. Estará disponible ASAP en la versión v1.4.
