### ISSUE TITLE
No se puede generar el certificado

### ISSUE THREAD

**Issue by amunozg** [kikeelectronico/Homeware-LAN#279]
Hola,

Estoy intentando desplegar Homeware en una Raspberry 3B con Docker y me está siendo imposible debido a que el certificado no se genera.

He utilizado la última imagen de Raspbian, he actualizado el sistema e instalado Docker. Al realizar "docker-compose up" para ver el log en tiempo real el contenedor de letsencrypt arroja errores de conexión (curl error 6), adjunto el log.

Si finalizo la configuración con http puedo acceder al frontend sin problemas, pero por https me rechaza la conexión.

Como información extra puedo decir que puedo hacer ping desde el host a los contenedores, y desde los contenedores entre sí, pero desde el contenedor de letsencrypt no, ya que da el error "ping: clock_gettime(MONOTONIC) failed". También decir que es el único que tiene como fecha del sistema 01/01/1970.

¿Alguna sugerencia?
Gracias!!

[homeware_log.txt](https://github.com/kikeelectronico/Homeware-LAN/files/6364878/homeware_log.txt)

**Comment by amunozg** [comment]
Hola, ¿alguien ha podido probar si obtiene un resultado distinto en su log? Ya me da por pensar que podría ser normal pero estoy haciendo alguna otra cosa mal.

Muchas gracias

**Comment by kikeelectronico** [comment]
No consigo reproducirlo. ¿Has configurado el archivo .env antes de empezar?

https://kikeelectronico.github.io/Homeware-LAN/docs/install

**Comment by amunozg** [comment]
Sí, he añadido el fichero .env en la carpeta Homeware-LAN y en el log veo el correo que he indicado.

Previamente con un programa en node he probado que la comunicación llega bien por el 80 y el 443, pero he vuelto a descargar las imágenes y lanzar docker-compose y me pasa exactamente lo mismo. El puerto 80 si responde pero el 443 no (connection refused), y el log es igual:

`
...
letsencrypt_1              | 2021/05/22 16:46:20 Generated '/app/letsencrypt_service_data' from 12 containers
letsencrypt_1              | 2021/05/22 16:46:20 Running '/app/signal_le_service'
letsencrypt_1              | 2021/05/22 16:46:20 Watching docker events
letsencrypt_1              | 2021/05/22 16:46:20 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
letsencrypt_1              | [Thu Jan  1 00:00:00 UTC 1970] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
letsencrypt_1              | [Thu Jan  1 00:00:00 UTC 1970] Can not init api.
letsencrypt_1              | [Thu Jan  1 00:00:00 UTC 1970] Create account key ok.
letsencrypt_1              | [Thu Jan  1 00:00:00 UTC 1970] Registering account: https://acme-v02.api.letsencrypt.org/directory
letsencrypt_1              | [Thu Jan  1 00:00:00 UTC 1970] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
...
`

¿Qué más podría comprobar?
Gracias

**Comment by amunozg** [comment]
Hola de nuevo, he hecho una prueba esta vez en una Raspberry 4b y he tenido los mismos resultados.

**Comment by kikeelectronico** [comment]
He creado un nuevo archivo docker-compose para Raspberry Pi. Echad un vistazo a las instrucciones actualizadas en el README.

**Comment by amunozg** [comment]
Buenos días,

He probado de nuevo en RPI con un docker limpio y da error al levantar el contenedor homeware-lan_homeware-lan-back-api_1.

El error es el siguiente:

> ERROR: for homeware-lan-back-api  Cannot start service homeware-lan-back-api: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "gunicorn": executable file not found in $PATH: unknown
> ERROR: Encountered errors while bringing up the project.

Gracias!

**Comment by kikeelectronico** [comment]
@amunozg no consigo averiguar que está pasando. ¿Puedes volver a instalar desde cero? Asegúrate tener el repositorio actualizado en tu RPi.

https://kikeelectronico.github.io/Homeware-LAN/docs/install

**Comment by amunozg** [comment]
Buenos días,

Acabo de probar todo desde cero y ha ido bien. He realizado el proceso completo.

En un momento vi errores de mqtto y porque el contendor se paró pero al poner el usuario y clave en la interfaz y reiniciar con compose-down/up todo quedó estable.

Muchas gracias!

PD: Solo una pregunta, ¿se podría utilizar un mqtto que ya tengamos instalado en lugar de utilizar el defindo en docker-compose.yaml? ¿funcionaría solo modificando la línea "MQTT_HOST=mosquitto" o habría inconvenientes? Gracias!

**Comment by kikeelectronico** [comment]
Efectivamente tendrías que cambiar MQTT_HOST
