### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ezebrizzio** [kikeelectronico/Homeware-LAN#289]
Eventualmente, la representación del set-point de los termostato sufre algún tipo de "redondeo" o "interpretación"

"thermostatTemperatureSetpoint":float24.9383602142334

![image](https://user-images.githubusercontent.com/11993232/124914906-45f37080-dfc7-11eb-99b4-f6fbc5ae0244.png)

- OS: ubuntu 20.04

**Comment by kikeelectronico** [comment]
No encuentro ningún punto del código de Homeware dónde pueda estar ocurriendo esto. Lo seguiré monitorizando a largo plazo.
