### ISSUE TITLE
Bug_Login

### ISSUE THREAD

**Issue by lucasdellasantina96** [kikeelectronico/Homeware-LAN#29]
Después de hacer un logout no te permite volver a loguear a la pagina,  tampoco te deja  despues de reiniciar el host (systemctl restart homeware), la petición llega pero el server no le contesta. La única forma que encontré es levantarlo de 0 pero igualmente vuelve a suceder, para mi hay algun servicio que no se está levantando, quizás fernet ? no lo se..

**Comment by kikeelectronico** [comment]
Puedes confirmarme en que versión de Homeware-LAN te ocurre y si has borrado caché y forzado la recarga en el navegador.

**Comment by lucasdellasantina96** [comment]
Realice un pull  con la (Latest release) “v0.4.1”pero la version del data.py  es “version = 'v0.4' ” y  limpie la caché para borrar el token de autenticación. :)

**Comment by kikeelectronico** [comment]
Vale, por último,

1. Verifica que te sale en el navegador si intentas acceder a:
- tu.dominio.com/test/
- laipdeturaspberry:5001/test/ por ejemplo http://192.168.1.50:5001/test/

2. ¿Qué se muestra en la consola del navegador si intentas hacer el login? Puedes abrirla con la tecla F12

**Comment by lucasdellasantina96** [comment]
1. 
- tu.dominio.com/test/
load
- laipdeturaspberry:5001/test/ por ejemplo http://192.168.1.50:5001/test/
load 

2.  500 INTERNAL SERVER ERROR
https://ibb.co/j6Fkb8H

**Comment by kikeelectronico** [comment]
Lo analizaré

**Comment by kikeelectronico** [comment]
No consigo reproducir el error que comentas. Actualiza la versión de Homeware a la nueva release, usa ```Ctrl+Shift+R``` para forzar la recarga y borra las cookies ```token``` y ```user```.

https://github.com/kikeelectronico/Homeware-LAN/releases/tag/v0.5

**Comment by kikeelectronico** [comment]
Usa esta, la anterior es incorrecta: https://github.com/kikeelectronico/Homeware-LAN/releases/tag/v0.5.1
