### ISSUE TITLE
Url de mosquito

### ISSUE THREAD

**Issue by VasquezLab** [kikeelectronico/Homeware-LAN#304]
He subido un servidor cloud para el proyecto en https://smart.anvargear.co/

Estoy realizando la conexión desde mi dispositivo ESP32, peor me dice que no se conecta al servidor de mosquitto, estoy utilizando el ejemplo pero el solo dice poner IP del Raspberry PI, pero en mi caso cual seria?

Quedo atento a cualquier ayuda.

**Comment by VasquezLab** [comment]
@ajpl no se que pueda estar haciendo mal.

Di permisos al puerto 1883 como TCP, intento ingresar a http(s)://smart.anvargear.co:1883  y no logro tener conexión, hice un telnet y pues tuve respuesta pero hasta ahí.

Estuve usando este código como ejemplo https://github.com/kikeelectronico/Homeware-LAN/blob/master/ESP8266example/ESP8266example/ESP8266example.ino

**Comment by kikeelectronico** [comment]
Me alegro de que se haya resulto. Siento no haber llegado antes.
