### ISSUE TITLE
[Feature] Agregar el dispositivo de  Pet Feeder

### ISSUE THREAD

**Issue by VasquezLab** [kikeelectronico/Homeware-LAN#307]
Dar la posibilidad de agregar el dispositivo  **[Pet Feeder,](https://developers.google.com/assistant/smarthome/guides/petfeeder)** con lo cual es necesario agregar el trait nuevo llamado **[Dispense](https://developers.google.com/assistant/smarthome/traits/dispense)**

Estoy empezando agregarlo en mi folk, para liberarlo a la comunidad.

- [x]  Crear constant params Front
- [x] Crear constant trait Front 
- [x] Crear constant device Front
- [x] Crear componente trait Front
- [x] Crear componente Device Front
- [ ] Agregar el device en el Back
- [ ] Realizar pruebas

**Comment by kikeelectronico** [comment]
Genial @VasquezLab. Avísame si hay algo en lo que pueda ayudar.

**Comment by VasquezLab** [comment]
Se realiza todo la sección del front con el pull request #309

**Comment by VasquezLab** [comment]
@kikeelectronico  sabes estoy un poco perdido en el Back, como es el funcionamiento del command y state. Me puedes dar una mano, para continuar.

**Comment by kikeelectronico** [comment]
@VasquezLab voy a estar un poco liado hasta media semana. Intento documentar esa parte, el miércoles o el jueves.
