### ISSUE TITLE
Problem Temp Interior

### ISSUE THREAD

**Issue by xabibix** [kikeelectronico/Homeware-LAN#31]
Buenos días, quiero realizar un termostato con un ESP8266 + DHT11, he conseguido enlazar el termostato en Google Home ,pero no consigo enviar el dato de la temperatura del DH11 y verlo donde pone temperatura interior, (siempre me aparece 22ºC).

Para la publicación del dato de temperatura utilizo esta linea en el código del ESP8266 : client.publish("device/temp", String(temp).c_str(), true);

**Comment by kikeelectronico** [comment]
¿Qué versión de Homeware has instalado?

**Comment by xabibix** [comment]
La última actualizada, 0.4.1

**Comment by kikeelectronico** [comment]
Revisa el ejemplo de código para termostato en está nueva release. Reabre la issue si sigues con él sigues sin poder enviar datos.

https://github.com/kikeelectronico/Homeware-LAN/releases/tag/v0.5

**Comment by kikeelectronico** [comment]
Usa esta, la anterior es incorrecta: https://github.com/kikeelectronico/Homeware-LAN/releases/tag/v0.5.1

**Comment by xabibix** [comment]
Termostato funcionando, que grande!!!! 🙏

**Comment by xabibix** [comment]
Hola, como te dije ayer, el termostato me funciona con NODEMCU 1.0 +
BME280 , pero me he dado cuenta que cada 10 o 12 segundos me aparece en
bucle este mensaje en el puerto serie, estoy investigando a ver de que
puede ser, en el ejemplo de la bombilla me funciona todo bien, sin bucles.
También me tiene mosca esta linea :  Message arrived [device/termostato]
18.00, siempre con temperatura 18.

Muchas gracias, saludos.

12:01:27.240 -> Connecting to MOVISTAR_31A4
12:01:27.307 -> ....
12:01:32.132 -> WiFi connected
12:01:32.132 -> IP address:
12:01:32.132 -> 192.168.1.50
12:01:34.234 -> Sensor Ok
12:01:34.234 -> Attempting MQTT connection...connected
12:01:36.259 ->
{"id":"termostato","param":"thermostatTemperatureAmbient","value":22,"intent":"rules"}
12:01:38.262 -> Message arrived [device/termostato] 18.00
12:01:38.262 -> 18.00
12:01:38.262 ->
12:01:38.262 -> Exception (28):
12:01:38.262 -> epc1=0x4020cca2 epc2=0x00000000 epc3=0x00000000
excvaddr=0x00000000 depc=0x00000000
12:01:38.296 ->
12:01:38.296 -> >>>stack>>>
12:01:38.296 ->
12:01:38.296 -> ctx: cont
12:01:38.296 -> sp: 3ffffc50 end: 3fffffc0 offset: 01a0
12:01:38.296 -> 3ffffdf0:  3ffffee4 00000000 3ffeea80 40202002
12:01:38.296 -> 3ffffe00:  3ffffe1c 3ffffe1c 3ffffee4 3ffffee4
12:01:38.296 -> 3ffffe10:  41900000 3ffeebf4 3ffee90c 3ffe878e
12:01:38.296 -> 3ffffe20:  00000000 3ffe878d 3ffffed0 4020e3bb
12:01:38.296 -> 3ffffe30:  00000000 ffffffff ffffffff 00000000
12:01:38.296 -> 3ffffe40:  00000000 00000000 0000001f 4010017c
12:01:38.331 -> 3ffffe50:  00000ad0 0000015a 0000015a 40100a78
12:01:38.331 -> 3ffffe60:  00000000 4bc6a7f0 a0418937 00000001
12:01:38.331 -> 3ffffe70:  3ffefcfc 00000000 00000020 40100d03
12:01:38.331 -> 3ffffe80:  00000000 00000000 4bc6a7f0 00000000
12:01:38.331 -> 3ffffe90:  00000000 00000001 00000000 40218758
12:01:38.331 -> 3ffffea0:  00000000 3fffc6fc 3ffef9e4 40212572
12:01:38.331 -> 3ffffeb0:  00321eae 00000000 3ffef9e4 4020331a
12:01:38.331 -> 3ffffec0:  00002b58 3fffff02 00000030 40203372
12:01:38.365 -> 3ffffed0:  00000015 3fffff02 3ffee7b8 40203778
12:01:38.365 -> 3ffffee0:  3ffee7c4 00000000 00000000 3ffee69a
12:01:38.365 -> 3ffffef0:  0001000a 00000000 00000000 00000000
12:01:38.365 -> 3fffff00:  00000004 3ffee7dd 0a0d0304 3ffeebb0
12:01:38.365 -> 3fffff10:  3fffff40 00000001 00000011 00000001
12:01:38.365 -> 3fffff20:  00000011 00002b58 3ffee7b8 40207bfc
12:01:38.365 -> 3fffff30:  3ffee7b8 00002b58 3ffee7b8 40203ebc
12:01:38.365 -> 3fffff40:  3ffedf01 3ffeecb8 000003e8 3ffee674
12:01:38.399 -> 3fffff50:  00000004 3ffee7bb 0000001a 40205b73
12:01:38.399 -> 3fffff60:  007a1200 bcda7bf2 3ffee7b8 3ffeebb0
12:01:38.399 -> 3fffff70:  3ffee7b8 00000000 3ffeeb70 402012c9
12:01:38.399 -> 3fffff80:  00000000 00000000 00000001 4010017c
12:01:38.399 -> 3fffff90:  3fffdad0 00000000 3ffeeb70 3ffeebb0
12:01:38.399 -> 3fffffa0:  3fffdad0 00000000 3ffeeb70 40205c88
12:01:38.399 -> 3fffffb0:  feefeffe feefeffe 3ffe85c4 40100fc5
12:01:38.433 -> <<<stack<<<
12:01:38.433 ->
12:01:38.433 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
12:01:38.433 ->
12:01:38.433 -> load 0x4010f000, len 1392, room 16
12:01:38.433 -> tail 0
12:01:38.433 -> chksum 0xd0
12:01:38.433 -> csum 0xd0
12:01:38.433 -> v3d128e5c
12:01:38.433 -> ~ld
12:01:38.500 ->

**Comment by xabibix** [comment]
Como te comente el lunes , el esp8266 se me reiniciaba cada 10 segundos,
modificando algunas cosillas ahora he observado que solo se me reinicia
cuando modifico algún valor del termostato dentro de Google Home, (cuando
funciona el void ( callback )),

Te pasa lo mismo con tu programa? te adjunto el código que utilizo:

#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>
#include <EEPROM.h>
#include <Wire.h>
#include <Adafruit_BME280.h>
#include <SPI.h>

//      This example receibes shows via serial port both the mode and the
temperature setpoint of the
// a thermostat. It alse send the real temperature reading the value froma
BME280 temperature sensor.

/* Remember to cahnge
 *  #define MQTT_MAX_PACKET_SIZE 128
 *  for
 *  #define MQTT_MAX_PACKET_SIZE 256
 *  in the PubSubClient library.
 */

 //Instructins
 //Change <thermostat-id> for the id of your thermostat in the line 125
 //Change <thermostat-id> for the id of your thermostat in the line 44
 //Change network setting:

const char* ssid = "MOVISTAR_31A4";
const char* password = "*****************";
const char* mqtt_server = "192.168.1.43";

//Objects
WiFiClient espClient;
PubSubClient client(espClient);
Adafruit_BME280 bme;

//General
long lastMsg = 0;
char msg[50];
int value = 0;
char json_c[200];
char deviceMode[30];
int temperatureSetPoint = 0;
int thermostatTemperatureAmbient = 0;
bool sendSetPoint = false;
bool showSetPoint = false;
long int tempUpdateTimeStamp = 0;
char requestA[100] =
"{\"id\":\"termostat\",\"param\":\"thermostatTemperatureAmbient\",\"value\":";
char requestB[50] = ",\"intent\":\"rules\"}";
char request[300];

//--------------------------------------------------------------setup_wifi()----------------------------------------

void setup_wifi() {

  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  randomSeed(micros());

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  delay(2000);

  //Connect to sensor
  Wire.begin(D1,D2);
  if (!bme.begin()) {
    Serial.println(F("Could not find the sensor, check wiring or I2C
address"));
  }  else {
    Serial.println(F("Sensor Ok"));
  }
}

//----------------------------------------------------------callback()----------------------------------

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
    json_c[i] = payload[i];
  }
  Serial.println();
  //Serial.println(json_c);

  StaticJsonDocument<200> doc;
  DeserializationError error = deserializeJson(doc, json_c);

  if (error) {
    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.c_str());
  } else {

    //You can use the different values of a thermostat
    //Example of a string value
    strcpy(deviceMode, doc[F("thermostatMode")]);
    //Example of a int value
    temperatureSetPoint = doc[F("thermostatTemperatureSetpoint")];

    Serial.print(deviceMode);
    Serial.print(" - ");
    Serial.println(temperatureSetPoint);

  }

}

//-------------------------------------------------------reconnet()-------------------------------------
void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Create a random client ID
    String clientId = "ESP8266Client-";
    clientId += String(random(0xffff), HEX);
    // Attempt to connect
    if (client.connect(clientId.c_str())) {
      delay(2000);
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("device/control", "hello world");
      // ... and resubscribe
      client.subscribe("device/termostat");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}
//------------------------------------------------------------setup()--------------------------------------------------------
void setup() {
  Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}
//------------------------------------------------------------loop()-------------------------------------------
void loop() {

  if (!client.connected()) {
    reconnect();
  }
  client.loop();

  //Send temperature to Homeware
  char thermostatTemperatureAmbientBuf[2];
  //Read the rempetarure from the sensor
  int i=bme.readTemperature()-1;
  //If the ambient temperature has change
  if(thermostatTemperatureAmbient != i){
    //Convert the int variable from the sensor into a string variable.
    sprintf(thermostatTemperatureAmbientBuf, "%d", i);
    //Prepare the MQTT request with the temperature value.
    strcpy(request, requestA);
    strcat(request, thermostatTemperatureAmbientBuf);
    strcat(request, requestB);
    //Send the request
    client.publish("device/control", request);
    Serial.println(request);
    thermostatTemperatureAmbient = i;
  }
  delay(1000);
}

Muchas gracias, saludos.
