### ISSUE TITLE
[BUG] curl failed to verify the legitimacy 

### ISSUE THREAD

**Issue by messplay** [kikeelectronico/Homeware-LAN#338]
**Describe el bug**
Se me presenta el error para verificar el archivo .env lo cree con mi correo y el dominio "midominio.dds.net" no se si haga falta poner el http... en este archivo

despues de generar el docker compose

homeware-lan_nginx-proxy_1 is up-to-date
homeware-lan_redis_1 is up-to-date
homeware-lan_letsencrypt_1 is up-to-date
homeware-lan_mosquitto_1 is up-to-date
homeware-lan_homeware-lan-back-tasks_1 is up-to-date
homeware-lan_homeware-lan-back-api_1 is up-to-date
homeware-lan_homeware-lan-back-mqtt_1 is up-to-date
Recreating homeware-lan_nginx_1 ... done

luego le doy curl -d '{"user":"XX", "pass":"xx"}' -H "Content-Type: application/json" -X POST https://midominio.ddns.net/api/user/set/
recibo el siguiente error:

curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Si le incluyo la opcion -k para evitar el certificado SSL me sale  503 Service Temporarily Unavailable, estoy en una rpi4. alguna opcion?

**Comment by kikeelectronico** [comment]
Puede tardar unos minutos en estar disponible el certificado. Vuelve a ejecutar el comando de CURL y me cuentas.

El error 503 se produce cuando el dominio con el que estás accediendo a Homeware no es el que se configuró.

**Comment by messplay** [comment]
Hola, muchas gracias por la rpta, El formato en el archivo .env debe incluir el https...? o solo el nombre del dominio porque el que estor ingresando es que tengo registrado en noip

**Comment by kikeelectronico** [comment]
Debe ir sin https. Por ejemplo: ```www.google.com```

**Comment by messplay** [comment]
Listo bueno,/he corrido nuevamente el curl y ahora obtego esto
curl: (7) Failed to connect to ticon.ddns.net port 443: Conexión rehusada
curl: (7) Failed to connect to ticon.ddns.net port 443: Conexión rehusada

He verificado que noip apunte a mi ip y doble verificado que tengo abierto los puertos 80 y 443. Alguba sugerencia. Tambien te queria consultar si tenias copia de laversion anterior que me funcionaba muy bien. Solo que la sd donde la tenia instalada se danio, sigo intentado lo qme vayas recomendando

**Comment by messplay** [comment]
Ahora un clavo mas traet de correr nuevamente eldocker y,,.....
ERROR: for mosquitto  Cannot start service mosquitto: driver failed programming external connectivity on endpoint homeware-lan_mosquitto_1 (078dcecc8c63c4270a7f3352e7b9cff0904360d0cb257299fd61e63417ba7134): Error starting userland proxy: listen tcp4 0.0.0.0:1883: bind: address already in use

**Comment by messplay** [comment]
Bueno aunque aun no lo hago funcionar si he podido avanzar respecto al error de la conexion rehusada en el puerto 443 aca les describo la solución tomado de este [enlace](https://justwebu.com/solved-curl-error-7-failed-to-connect-to-domain-com-port-443-connection-refused-vestacp.html)

What is the Problem?
cURL error 7: Failed to connect to domain.com port 443: Connection refused

What is the solution?
The curl 7 error problem is very annoying. If you have VPS with vestacp installed, then this is a common problem.

To solve Curl 7 error in wordpress, you need to edit the hosts file in your VPS using SSH prompt. In the hosts file you need to add your ip address and domain name manually.

To solve cURL 7 error in vestacp as well as any vps follow the instructions.

Step 1: Log in to your server using SSH
First try

curl yourdoman.com
It will returet with the curl 7 error failed to connect to yourdomain.com using port 80.

Next try

curl https://yourdomain.com
The problem should be same as previous one, only the difference is port 443.

Now try

curl -vv yourdoman.com
Here the problem is same. can not rebuilt curl bla bla bla…

Enough, now we should try to solve this.

Step 2: Edit the following file (hosts file) using a nano or vim editor.
nano /etc/hosts
It should be look like this

127.0.0.1 localhost
127.0.1.1 yourdomain.com
The following lines are desirable for IPv6 capable hosts
:1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
Enter the following line after the second line

xx.xx.xx.xx yourdomain.com
Note: Replace xx.xx.xx.xx by your server ip address; and yourdomain.com by your fqdn or host domain.

So that the final code looks like this

127.0.0.1 localhost
127.0.1.1 yourdomain.com
xx.xx.xx.xx yourdomain.com
The following lines are desirable for IPv6 capable hosts
:1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

ahora obtengo el siguiente error 


curl: (6) Could not resolve host: POST
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mydomain:443

**Comment by messplay** [comment]
Bueno les comento que el problema no lo pude solucionar del todo , pero pude realizar la instalacion, desconozco el motivo pero tuve que cambiar a la versión de rpi legacy y todo funciono como debería. con la actual Raspberry Pi OS del 30 de oct de 2021 no me fue posible realizar la instalacion. Espero que la solución le sirva a alguien mas.
