### ISSUE TITLE
Problema al arrancar el servicio

### ISSUE THREAD

**Issue by toniht88** [kikeelectronico/Homeware-LAN#34]
Hola Enrique. Lo primero felicidades por el vídeo. Quisiera saber si se puede instalar en una BeagleBone por ejemplo, porque he visto que el servicio para que se arranque hace referencia siempre al directorio PI de Raspberry. Quisiera saber si se fue ejecutar en una Beaglenone y que parámetros se tendrían que modificar. Gracias.
Pd. El usuario de BB es ubuntu. He modificado la ruta del py dentro del servicio  para el usuario /home/ubuntu/ y sigue dando error.

**Comment by toniht88** [comment]
Arrancando la app manualmente he conseguido configurar todo y funciona perfectamente. Compatibilidad con Beaglebone con versión 18.04. La app es una maravilla y lo bien documentado que esta todo se merece mi enhorabuena. Mil gracias por el aporte.

**Comment by kikeelectronico** [comment]
Genial. Cierro la issue.
