### ISSUE TITLE
Funcionan los comandos desde la aplicacion pero no los de voz

### ISSUE THREAD

**Issue by messplay** [kikeelectronico/Homeware-LAN#363]
Saludos, despues de un buen tiempo logre instalar la aplicación, sin embargo tengo una consulta. Ya he sincronizado el equipo, sin embargo cuando le doy comandos de voz al asistente este no lo identifica (a pesar de que esta registrado como se ve en la pantalla), además de esto cuando le doy órdenes desde la aplicacion las luces prenden y apagan pero me sale este mensaje. También he visto que la respuesta es un poco mas lenta que en anteriores versiones (no se si sea relevante). En resumen los comandos de voz desde el asistente no funcionan(el asistente responde:"parece que el dispositivo no esta configurado aún); por otro lado si le doy la orden desde el google home(y desde el servidor) si las atiende pero sale el mensaje de la imagen. Quedo atento si tienen alguna sugerencia
![image](https://user-images.githubusercontent.com/5551700/151211218-7a277b9a-e615-4b66-9843-1d3312b1d162.png)

**Comment by kikeelectronico** [comment]
Hola @messplay no estoy seguro que ocurre pero tiene pinta de que Homeware o la Raspberry están tardando demasiado en responder. Intenta ver el tiempo de puesta de tu Homeware usando una herramienta del tipo https://check-host.net/check-http
