### ISSUE TITLE
Grammar mistake and a Guide on how to deploy Homeware on Windows

### ISSUE THREAD

**Issue by ljcmps01** [kikeelectronico/Homeware-LAN#57]
On the Wiki section How To>Communicate a Hardware device with Homeware LAN>Topics>Examples:
"Due to the data **sended** by Homeware[…]"
"sended" should be replaced by "sent"

Also, A guide on how to deploy the server on Windows is greatly needed, newbies like me would appreciate it a lot

**Comment by kikeelectronico** [comment]
I have corrected the grammar mistake. Thanks!

I will analyze the possibility of the guide How to deploy Homeware-LAN on Windows. By now it only has been tested on Raspbian.

**Comment by kikeelectronico** [comment]
For now, Hit will not be documented for Windows.
