### ISSUE TITLE
Servicio homewareRedis.service no se inicia

### ISSUE THREAD

**Issue by fernanst** [kikeelectronico/Homeware-LAN#60]
Falta la carpeta /home/pi/Homeware-LAN/redis/redis-stable/

**Comment by kikeelectronico** [comment]
1 - ¿Qué versión de Homeware-LAN tienes instalada?
2 - Te falta después de instalar o después de actualizar?
3 - En caso de ser después de actualizar ¿Qué versión tenías antes?

**Comment by fernanst** [comment]
Hola Enrique:

Es una instalación nueva, pero ya he conseguido completar la instalación,
he usado el install.sh que tienes en la rama develop que instala y compila
REDIS y además copia los .services en systemd.
Ahora me está dando un error al realizar test desde la web de google
assistant hacia las Raspberry, pero creo es problema del dominio. Sigo
haciendo pruebas.

Saludos.
Fernando Santo Tomas

**Comment by kikeelectronico** [comment]
Entiendo que ya está solucionado. Cierro la issue.
