### ISSUE TITLE
can't update setting check your connection in smart home app

### ISSUE THREAD

**Issue by naga-master** [kikeelectronico/Homeware-LAN#65]
I created actions in google home as per your document , in my smart home app i can see test home but when i try to link account it say **can't update setting check your connection**.i surfed on google nothing helped me..please resolve this..and i tried homeware-firebase also the same error happens that too.

**Comment by kikeelectronico** [comment]
I have just released v0.7. Now you can check the events log from the settings page. It is possible that the log shows you where is the problem.

Update to v0.7, check the Events log and tell me what is the error.
