### ISSUE TITLE
problema Ngix en  RPI zero W

### ISSUE THREAD

**Issue by messplay** [kikeelectronico/Homeware-LAN#79]
Le pedi mucho a la W zero?, existe alguna posibilidad de lograrlo?

**Comment by messplay** [comment]
Logre instalarlo en una RPI zero W y los servicios aparece **active(running)** sin embargo cuando intento entrar desde el navegador en otro pc a la raspberrypiIP:5001 aparece ERR_CONNECTION_REFUSED, y no carga lo que supongo debe ser una pagina de configuracion. Alguna sugerencia?

**Comment by messplay** [comment]
Parece existir un problema en el servidor ngix 

sep 03 19:23:42 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
sep 03 19:23:43 raspberrypi nginx[15077]: nginx: [emerg] invalid number of arguments in "server_name" directive in /etc/nginx/sites-enabled/default:3
sep 03 19:23:43 raspberrypi nginx[15077]: nginx: configuration file /etc/nginx/nginx.conf test failed
sep 03 19:23:43 raspberrypi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
sep 03 19:23:43 raspberrypi systemd[1]: nginx.service: Failed with result 'exit-code'.
sep 03 19:23:43 raspberrypi systemd[1]: Failed to start A high performance web server and a reverse proxy server.

la configuracion del archivo en cuestion la probado asi:
server {
        listen 80 default_server;
        server_name domain;

        location / {
                proxy_pass http://127.0.0.1:5001;
        }
}

y asi 

server {
        listen 80 default_server;
        server_name ;

        location / {
                proxy_pass http://127.0.0.1:5001;
        }
}

sin exito, alguna recomendacion?

**Comment by messplay** [comment]
Bueno para el que le pueda servir cuento mi experiencia, estoy trabajando en una RPI_Zero_W lo intente por varios días con una instalacion de escritorio de Raspbian, hoy cambie a una version de sólo consola, primero hice los pasos manualmente del archivo install.bash, y no funciono, pero luego volvi a correr el install.bash y ya accede al servidor por el puerto 5001. No tengo muy claro que soluciono el problema, pero lo que sirvio fue reinstalar el OS de la rpi

**Comment by kikeelectronico** [comment]
Lo revisaré
