### ISSUE TITLE
Json editor not available in edit mode

### ISSUE THREAD

**Issue by messplay** [kikeelectronico/Homeware-LAN#80]
Greetings, I have been checking your system and trying to edit the modes, I tried using the json editor, but two things happen, first it seems that it saves them, and once saved it does not allow access to the editor to correct any failure, so the mode option, seems to be inoperative at this time

**Comment by kikeelectronico** [comment]
What Homeware-LAN version are you using? Where this issue happend, Task editor or Rules editor?

**Comment by messplay** [comment]
GRacias te voy a escribir en ambos idiomas por comodidad, estoy usando la ultima versión Homeware-LAN 0.7. El problema realmente en el apartado de agregar dispositivo, cuando quiero escribir los Json de los modos, por ejemplo FAN o AC que tienen habilitada esta opción, en el momento de crear el dispositivo permite ingresar los Json, pero no los guarda y posteriormente no los permite editar una vez el dispositivo ha sido creado. 

Thanks, I'll write to you in both languages for convenience, I'm using the latest Homeware-LAN 0.7 version. The problem really in the section of adding device, when I want to write the Json of the modes, for example FAN or AC that have this option enabled, at the time of creating the device it allows entering the Json, but it does not save them and later not them allows editing once the device has been created.

**Comment by kikeelectronico** [comment]
Modes are not supported in version v0.7. However, they will be in the next review.
Los modos no están soportados en la versión v0.7. Sin embargo, si lo estaran en la siguiente revisión.
