### ISSUE TITLE
EasyESP esp-01s relay v1.0

### ISSUE THREAD

**Issue by betojsp** [kikeelectronico/Homeware-LAN#81]
Hello, this hardware is very easy to configure with EasyESP to configure the relay.

<img width="150" alt="esp-01s relay v1.0" src="https://user-images.githubusercontent.com/45493366/93145294-95bc2080-f6b1-11ea-9a28-03a43ac4e648.jpg">

The esp connects to the broker without problem, the payload that Homeware delivers in json cannot be parsed, is it possible to modify the payload for this relay?

<img width="450" alt="Captura de Pantalla 2020-09-14 a la(s) 5 46 06 p  m" src="https://user-images.githubusercontent.com/45493366/93147595-50025680-f6b7-11ea-9528-fad42beb1e29.png">

**Example payload**

**Homeware**

MSG: {"online": true, "on": true}
Topic: device/bea-5974C2

**mqtt-client**

On
MSG: 1
Topic: device/bea-5976f7/gpio/0

Off
MSG: 0
Topic: device/bea-5976f7/gpio/0

**Comment by kikeelectronico** [comment]
No. It is not in the designed that way.
