### ISSUE TITLE
Failed authorization procedure.

### ISSUE THREAD

**Issue by pgtarazonag** [kikeelectronico/Homeware-LAN#82]
habilito todos los puertos del router, sigo el tutorial al pie de la letra pero al intentar obtener el certificado ssl obtengo este error. Failed authorization procedure. (ya verifique las recomendaciones que dan=

**Comment by betojsp** [comment]
@pgtarazonag Letsencrypt puede bloquear la ip si se realizan muchas solicitudes para la creación del certificado.

**Comment by pgtarazonag** [comment]
@betojsp Gracias por reponder, que alternativa me recomienda para solucionar este error?

**Comment by betojsp** [comment]
Personalmente tengo mi dominio en cloudflare free y utilizó el siguiente script [https://gist.github.com/Tras2/cba88201b17d765ec065ccbedfb16d9a](https://gist.github.com/Tras2/cba88201b17d765ec065ccbedfb16d9a) para actualizar la ip. Cloudflare crea el certificado y hace un proxy a tu ip

**Comment by kikeelectronico** [comment]
1. Verifica que el dominio se dirige a la IP correcta.

Puedes usar:
```ping tu.dominio.com``` 
desde un terminal para averiguar la IP asignada al dominio y después usar una web http://www.cualesmiip.com/ para vericiar cual es tu ip pública.

2. Verifica que el puerto 80 del router se redirige al 80 de la raspberry pi.
3. Verifica que el puerto 443 del router se redirige al 433 de la raspberry pi.
