### ISSUE TITLE
Resetear instalacion

### ISSUE THREAD

**Issue by messplay** [kikeelectronico/Homeware-LAN#90]
SAludos, tengo una consulta existe alguna forma de "poner" la instalación "como de fabrica" o de llevarla nuevamente al wizard inicial sin necesidad de correr nuevamente el archivo bash o borrar la carpeta y reinstalar?. LEs cuento que he intentando instalar el Homeware en una instalación fresca de la RPI Z W, pero se presentaron los mismos problemas de la primera vez, asi que tome una imagen que habia guardado de backup, el unico problema es que ya en esa RPI habia corrido el Wizard. Alguna recomendación?

**Comment by betojsp** [comment]
hola, creo que puede ser un redis-cli FLUSHDB [https://www.cyberciti.biz/faq/how-to-flush-redis-cache-and-delete-everything-using-the-cli/](https://www.cyberciti.biz/faq/how-to-flush-redis-cache-and-delete-everything-using-the-cli/)

**Comment by messplay** [comment]
De una voy a probar y les cuento

**Comment by messplay** [comment]
Funciono perfectamente, muchas gracias.
