### ISSUE TITLE
Topic Status

### ISSUE THREAD

**Issue by betojsp** [kikeelectronico/Homeware-LAN#91]
Hola, ¿ que topic tengo que utilizar para reportar el estado del dispositivo y que payload utilizo ?

_**Gracias y saludos**_

**Comment by kikeelectronico** [comment]
Puedes encontrar la información en la Wiki https://github.com/kikeelectronico/Homeware-LAN/wiki/Communicate-a-hardware-device-with-Homeware-LAN
