### ISSUE TITLE
Nuevo Device

### ISSUE THREAD

**Issue by messplay** [kikeelectronico/Homeware-LAN#92]
Saludos gente, quisiera agregar un nuevo devices que no esta en la lista tipo "sensor", con una lista propia de traids, que archivos deberia modificar para que aparezca en el asistente y sea funcional?

**Comment by kikeelectronico** [comment]
Puedes decargar el archivo de backup e incluir el dispositivo a mano dentro de la clave `devices` y su estado dentro de la clave `status`. Cuando lo tengas, sube el archivo con la función de _Restore_.

El dispositivo sensor estará disponible en la siguiente versión (v1.0) programada para el día 24/10/2020

**Comment by messplay** [comment]
Amigo, muchas gracias
